//
// Created by Patrick on 2024-04-10.
//

#ifndef DRIFT_WHEELENCODER_H
#define DRIFT_WHEELENCODER_H

#include "encoderDriver.h"

enum wheelDirection {
    LEFT,   // 0
    RIGHT   // 1
};

/**
 * @class wheelEncoder
 * @brief Class representing a wheel encoder.
 */
class wheelEncoder {
public:
    wheelEncoder();

    int32_t readLeftSpeed();

    int32_t readRightSpeed();

    /**
    * @brief Handle interrupt generated by the wheel encoder.
    */
    volatile void handleInterrupt();

private:
    encoderDriver leftWheel;    /**< Encoder driver for the left wheel. */
    encoderDriver rightWheel;   /**< Encoder driver for the right wheel. */
};


#endif //DRIFT_WHEELENCODER_H
